# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_q_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='q_role',
            new_name='quran_class',
        ),
    ]
