# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170806_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='islamic_studies_class',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'IS1'), (2, 'IS2'), (3, 'IS3'), (4, 'IS4'), (5, 'IS5'), (6, 'IS6'), (7, 'IS7'), (8, 'IS8'), (9, 'IS9')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quran_class',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4'), (5, 'Q5'), (6, 'Q6'), (7, 'Q7'), (8, 'Q8'), (9, 'Q9')], null=True),
        ),
    ]
