# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170809_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qurancomment',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='quranpost',
            old_name='text',
            new_name='message',
        ),
    ]
