# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20170809_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qurancomment',
            name='author',
            field=models.TextField(),
        ),
    ]
