# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0012_auto_20170809_0455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quranpost',
            unique_together=set([('author', 'message')]),
        ),
    ]
