# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0014_auto_20170809_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslamicStudiesComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IslamicStudiesPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='')),
                ('class_level', models.PositiveSmallIntegerField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islamic_studies_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='qurancomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_comments', to='profiles.QuranPost'),
        ),
        migrations.AlterField(
            model_name='quranpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='islamicstudiescomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islamic_studies_comments', to='profiles.IslamicStudiesPost'),
        ),
        migrations.AlterUniqueTogether(
            name='islamicstudiespost',
            unique_together=set([('author', 'message')]),
        ),
    ]
