# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20170809_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='read_quran_posts',
            field=models.ManyToManyField(related_name='read_quran_posts', to='profiles.QuranPost'),
        ),
    ]
