# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_read_quran_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='read_quran_posts',
        ),
        migrations.AddField(
            model_name='profile',
            name='unread_quran_posts',
            field=models.ManyToManyField(related_name='unread_quran_posts', to='profiles.QuranPost'),
        ),
    ]
