# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20170809_2121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quranpost',
            unique_together=set([]),
        ),
    ]
