# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20170809_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_islamic_studies_comments',
            field=models.ManyToManyField(related_name='unread_islamic_studies_comments', to='profiles.IslamicStudiesComment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unread_islamic_studies_posts',
            field=models.ManyToManyField(related_name='unread_islamic_studies_posts', to='profiles.IslamicStudiesPost'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unread_quran_comments',
            field=models.ManyToManyField(related_name='unread_quran_comments', to='profiles.QuranComment'),
        ),
    ]
