# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_quranexams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuranExams',
            new_name='QuranExam',
        ),
    ]
