# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20170811_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuranExam',
            new_name='QuranExams',
        ),
    ]
