# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20170811_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quranexam',
            name='student',
        ),
        migrations.DeleteModel(
            name='QuranExam',
        ),
    ]
