# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0024_auto_20170811_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_number', models.PositiveSmallIntegerField(choices=[(1, 'Exam 1'), (2, 'Exam 2'), (3, 'Exam 3')])),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_taken', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_exam_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
