# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20170811_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='quranexam',
            name='class_level',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4'), (5, 'Q5'), (6, 'Q6'), (7, 'Q7'), (8, 'Q8'), (9, 'Q9')], null=True),
        ),
    ]
