# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 04:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0027_quranexam_class_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quranexam',
            unique_together=set([('student', 'exam_number')]),
        ),
    ]
