# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 05:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20170811_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='quranexam',
            name='exam_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
