# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20170811_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quranexam',
            name='date_taken',
        ),
    ]
