# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 04:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0032_remove_quranexam_date_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslamicStudiesExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_number', models.PositiveSmallIntegerField(choices=[(1, 'Exam 1'), (2, 'Exam 2'), (3, 'Exam 3')])),
                ('exam_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('class_level', models.PositiveIntegerField(blank=True, choices=[(1, 'IS1'), (2, 'IS2'), (3, 'IS3'), (4, 'IS4'), (5, 'IS5'), (6, 'IS6'), (7, 'IS7'), (8, 'IS8'), (9, 'IS9')], null=True)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islamic_studies_exam_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='islamicstudiesexam',
            unique_together=set([('student', 'exam_number')]),
        ),
    ]
