# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20170812_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unread_islamic_studies_comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='unread_islamic_studies_comments', to='profiles.IslamicStudiesComment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unread_islamic_studies_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='unread_islamic_studies_posts', to='profiles.IslamicStudiesPost'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unread_quran_comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='unread_quran_comments', to='profiles.QuranComment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unread_quran_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='unread_quran_posts', to='profiles.QuranPost'),
        ),
    ]
