# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0035_auto_20170812_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranWeeklyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('class_level', models.CharField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4'), (5, 'Q5'), (6, 'Q6'), (7, 'Q7'), (8, 'Q8'), (9, 'Q9')], max_length=20)),
                ('students_late', models.ManyToManyField(blank=True, related_name='students_late', to=settings.AUTH_USER_MODEL)),
                ('students_present', models.ManyToManyField(related_name='students_present', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
