# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0037_auto_20170817_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('class_level', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4'), (5, 'Q5'), (6, 'Q6'), (7, 'Q7'), (8, 'Q8'), (9, 'Q9')])),
                ('attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Tardy', 'Tardy')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='quranweeklyattendance',
            name='students_late',
        ),
        migrations.RemoveField(
            model_name='quranweeklyattendance',
            name='students_present',
        ),
        migrations.DeleteModel(
            name='QuranWeeklyAttendance',
        ),
    ]
