# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_auto_20170817_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolWeeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='quranattendance',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
