# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_auto_20170817_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolWeeks',
            new_name='SchoolWeek',
        ),
    ]
