# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_auto_20170817_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quranattendance',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.SchoolWeek'),
        ),
    ]
