# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0043_auto_20170817_0144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quranattendance',
            unique_together=set([('student', 'week')]),
        ),
    ]
