# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_auto_20170817_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unseen_quran_attendance',
            field=models.ManyToManyField(blank=True, related_name='unseen_quran_attendance', to='profiles.QuranAttendance'),
        ),
        migrations.AlterField(
            model_name='quranattendance',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='profiles.SchoolWeek'),
        ),
    ]
