# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_auto_20170817_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quranattendance',
            name='attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Tardy', 'Tardy'), ('N/A', 'N/A')], max_length=10),
        ),
    ]
