# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0046_auto_20170818_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslamicStudiesAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'IS1'), (2, 'IS2'), (3, 'IS3'), (4, 'IS4'), (5, 'IS5'), (6, 'IS6'), (7, 'IS7'), (8, 'IS8'), (9, 'IS9')], null=True)),
                ('attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Tardy', 'Tardy'), ('N/A', 'N/A')], max_length=10)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islamic_studies_attendance', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islamic_studies_attendances', to='profiles.SchoolWeek')),
            ],
        ),
        migrations.AlterField(
            model_name='quranattendance',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_attendances', to='profiles.SchoolWeek'),
        ),
        migrations.AlterUniqueTogether(
            name='islamicstudiesattendance',
            unique_together=set([('student', 'week')]),
        ),
    ]
