# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_auto_20170819_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unseen_islamic_studies_attendance',
            field=models.ManyToManyField(blank=True, related_name='unseen_islamic_studies_attendance', to='profiles.IslamicStudiesAttendance'),
        ),
    ]
