# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_profile_unseen_islamic_studies_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolweek',
            unique_together=set([('week_number', 'date')]),
        ),
    ]
