# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_profile_populated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
