# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0051_profile_parent_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='populated',
            new_name='activation_email_sent',
        ),
    ]
