# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_auto_20170822_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='activation_email_sent',
            new_name='populated',
        ),
    ]
