# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_auto_20170822_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='populated',
            new_name='original_population',
        ),
    ]
