# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_auto_20170822_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_google_sheets',
            field=models.BooleanField(default=False),
        ),
    ]
