# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0057_auto_20170829_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quran_class',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (4, 'Q4'), (6, 'Q6'), (7, 'Q7'), (8, 'Q8'), (9, 'Q9'), (10, 'Q10')], null=True),
        ),
        migrations.AlterField(
            model_name='quranattendance',
            name='class_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (4, 'Q4'), (6, 'Q6'), (7, 'Q7'), (8, 'Q8'), (9, 'Q9'), (10, 'Q10')], null=True),
        ),
        migrations.AlterField(
            model_name='quranexam',
            name='class_level',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (4, 'Q4'), (6, 'Q6'), (7, 'Q7'), (8, 'Q8'), (9, 'Q9'), (10, 'Q10')], null=True),
        ),
    ]
