# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0061_auto_20170910_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unseen_islamic_studies_attendance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unseen_quran_attendance',
        ),
    ]
